### ISSUE TITLE
Questions about data labeling

### ISSUE THREAD

**Issue by csyThomas** [vision-workshop/Track2#2]
In the dataset, there are some gaps labeled as shown in the figure.
![658027_4_4_TA07_02_20220-2147483635_05_0_1280_800_2080](https://user-images.githubusercontent.com/76508353/230811798-ebc9c111-7a36-4f9c-a4ba-f67f81e44602.jpg)
 I would like to know if this part of the data is labeled correctly

**Comment by vision-workshop** [comment]
Hi Thomas,

Thank you for your interest in the VISION Challenges!

Yes, this is an expected gap defect type in the given dataset. The three
attached image crops show only the part of the unit below the gap, which
makes it look like the gap is at the edge of the image.

Best,
The VISION Team

**Comment by csyThomas** [comment]
Thanks for your reply. So is the final evaluation indicator the sum of these 12 scores?
![image](https://user-images.githubusercontent.com/76508353/231109291-e0f2036d-2f3b-4952-8aff-d2e7e271bc34.png)

**Comment by vision-workshop** [comment]
Hi Thomas,

The final evaluation is the average of AP_{IOU 0.5:0.95} (the first row)
and AR_{IOU 0.5:0.95, MaxDets=100} (the 9th row).

Thanks,
Best,
The Vision Team
