### ISSUE TITLE
Generating the proper enviromnent

### ISSUE THREAD

**Issue by cugwu** [vision-workshop/Track2#3]
Hi, I have problems generating the environment for running the code. If I follow the steps here in the libraries I always end up with the error: "AssertionError: MMCV==1.7.1 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0."
If I follow the steps on the official MMDetection website (https://mmdetection.readthedocs.io/en/latest/get_started.html#installation) where in the new version instead of mmcv-full you can write simply mmcv, I keep having the error: "ImportError: cannot import name 'Config' from 'mmcv' (/opt/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/__init__.py)
"
A part from mmcv.Config there are also other imports that are not possible like DictAction, mmcv.runner etc. Do you have any suggestions to solve the problem? I've tried it on both Linux and MACOS operating systems, obtaining the same results.
Thanks in advance for the answer!

**Comment by Shancong-Mou** [comment]
Hi,

Thanks for poinitng out this issue. This is due to the update of MMdetection library. To solve this, we have fixed the version of packages used in this competition as:
    ```
    pip install -U openmim==0.3.6;
    mim install mmcv-full==1.7.1;
    pip install mmdet==2.28.2;
    ```
Please follow the steps in the tutorial and install again.
