### ISSUE TITLE
Problem about submitted the Console_slided.sgem.zip in Dev Phase.

### ISSUE THREAD

**Issue by GrandpaXun242** [vision-workshop/Track2#4]
Hello, I have some problem with `My Submissions` module in [Vision 23 Challenge Track 2](https://eval.ai/web/challenges/challenge-page/1935/overview)
## Description
> My submission is committed in Apr 11, 2023. Its status  always been `running`. It`s been 6days now.

![image](https://user-images.githubusercontent.com/85432480/232366197-bc4c418f-9534-4d64-b734-edceefc38e48.png)

## My operation
1. Do some Data Argument based on Train dataset named `Console_slided`.
2. Use `python Block2.py --datasets Console_sliced` to start trainning and obtatin the result file named `Console_sliced.segm.json`.
3. zip `Console_sliced.segm.json` to `Console_sliced.segm.zip`.
4. Make a submission to submit the `Console_sliced.segm.zip` by **evalal** command.
    ```shell
    # submit command 
    evalai challenge 1935 phase 3867 submit --file ./Console_sliced.segm.zip  --large
    ```

During training time , I only changed the Train Dataset Image  and annotation file named `_annotations.coco.json`.
Is there any problem with my operation?How to obtain the Stderr file？
![image](https://user-images.githubusercontent.com/85432480/232368703-937b8487-0fc6-4920-ab44-99ae374facee.png)
Thanks!

**Comment by vision-workshop** [comment]
Hi,

Can you please send me your submission file? I can try to submit and see if
there is anything wrong. Another question,l I saw you have a
success submission on April 6, what is the difference in your submitted
files on April 11 or April 15?

Thanks,
The Vision Team

**Comment by GrandpaXun242** [comment]
Hi , I`m glad to receive your reply.
## To reply the first question
I send 3 submission file（
[Apr_15_Console_sliced.segm.zip](https://github.com/vision-workshop/Track2/files/11267843/Apr_15_Console_sliced.segm.zip)
[Apr_6_Console_sliced.segm.zip](https://github.com/vision-workshop/Track2/files/11267848/Apr_6_Console_sliced.segm.zip)
[Apr_11_Console_sliced.segm.zip](https://github.com/vision-workshop/Track2/files/11267849/Apr_11_Console_sliced.segm.zip)
） for you, 
## To reply the second question
**The submission file description**
`Apr_6_Console_sliced.segm.zip`:  only unzip the Console_slided.zip which is downloaded from [Track2](https://eval.ai/web/challenges/challenge-page/1935/overview) as the train dataset ,and then start to execute `python Block2.py --datasets Console_sliced` . This file can get the result on `My Submissions` module.

`Apr_11_Console_sliced.segm.zip`: I do some augment based on the original `Console_slided.zip` , only changed the train dataset part.The number of original train dataset is 2226  and the number of augment train dataset is 4226.Each categories is added 500.

`Apr_15_Console_sliced.segm.zip`: The operation is same with `Apr_11`.The difference is that the category `gap` 's number is added 300.

I didn't changed this `Console_sliced.segm.json` generated by `train.py`. I only zip `Console_sliced.segm.json` to `Console_sliced.segm.zip`.
Thanks for you.
 > Hi, Can you please send me your submission file? I can try to submit and see if there is anything wrong. Another question,l I saw you have a success submission on April 6, what is the difference in your submitted files on April 11 or April 15? Thanks, The Vision Team

**Comment by vision-workshop** [comment]
Hi,

I submitted your Apr_15_Console_sliced.segm.zip
<https://github.com/vision-workshop/Track2/files/11267843/Apr_15_Console_sliced.segm.zip>
file
and it runs successfully. Could you please directly submit this .zip file
and see if it works?

Thanks,
best,
The Vision Team

**Comment by GrandpaXun242** [comment]
Hi, 
I will submit the `Apr_15_Console_sliced.segm.zip` .
Thanks a lot.
