### ISSUE TITLE
Rules of Track 2

### ISSUE THREAD

**Issue by cugwu** [vision-workshop/Track2#6]
I have doubts about the rules of this challenge. 
I was wondering if the rules listed on the official page of Challenge Track 1: Data-efficient Defect Detection, also apply to Track 2. More precisely, is it possible to use other public datasets released before February 26 2023, to train our algorithm that will generate the new dataset? Or use the datasets of the challenge Track 1 for the just mentioned purpose? 
Thanks in advance for your reply.

**Comment by vision-workshop** [comment]
Hi,

You are allowed to use other public datasets to generate the synthetic
dataset.

Thanks,
Best,
The VISION Team

**Comment by cugwu** [comment]
Thanks for the answer!
